name: Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - server/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mydalart-server"
          heroku_email: "neverlish@gmail.com"
          procfile: "web: npm run start:prod"
          appdir: "server"